services:
  db:
    image: postgres:15.6
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: nestjs-boilertemplate
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  redis:
    image: redis:6.2
    ports:
      - "6379:6379"

  smtp4dev:
    image: rnwood/smtp4dev
    ports:
      - "5000:80"
      - "2525:25"

volumes:
  postgres_data:
